Repository musabd96/Schoolsync, pull requests merged in 2024-01, with the labels that each got.

#15 Feature: Add React app
  ReactApp/ReactApp.Server/Controllers/WeatherForecastController.cs
  ReactApp/ReactApp.Server/Program.cs
  ReactApp/ReactApp.Server/Properties/launchSettings.json
  ReactApp/ReactApp.Server/ReactApp.Server.csproj
  ReactApp/ReactApp.Server/ReactApp.Server.http
  ReactApp/ReactApp.Server/WeatherForecast.cs
  ReactApp/ReactApp.Server/appsettings.Development.json
  ReactApp/ReactApp.Server/appsettings.json
  ReactApp/reactapp.client/.eslintrc.cjs
  ReactApp/reactapp.client/.gitignore
  ReactApp/reactapp.client/README.md
  ReactApp/reactapp.client/index.html
  ReactApp/reactapp.client/nuget.config
  ReactApp/reactapp.client/package.json
  ReactApp/reactapp.client/public/vite.svg
  ReactApp/reactapp.client/reactapp.client.esproj
  ReactApp/reactapp.client/src/App.css
  ReactApp/reactapp.client/src/App.jsx
  ReactApp/reactapp.client/src/assets/react.svg
  ReactApp/reactapp.client/src/index.css
  ReactApp/reactapp.client/src/main.jsx
  ReactApp/reactapp.client/vite.config.js
Labels: documentation

#120 Feature: Infrastrucre Repository for IStudentRepository add for all r…
  Domain/Models/Person/PersonModel.cs
  Infrastructure/Repositories/Student/IStudentRepositry.cs
  Infrastructure/Repositories/Students/IStudentRepositry.cs
  Infrastructure/Repositories/Students/StudentRepositry.cs
  Infrastructure/Repositories/Teachers/ITeacherRepositry.cs
  Infrastructure/Repositories/Teachers/TeacherRepositry.cs
Labels: feature

#166 160-feature-get-all-classroom
  Application/Commands/ClassRoom/AddClassRoom/AddClassRoomCommand.cs
  Application/Commands/ClassRoom/AddClassRoom/AddClassRoomCommandHandler.cs
  Application/Commands/ClassRoom/DeleteClassRoom/DeleteClassRoomCommand.cs
  Application/Commands/ClassRoom/DeleteClassRoom/DeleteClassRoomCommandHandler.cs
  Application/Commands/ClassRoom/UpdateClassRoom/UpdateClassRoomCommand.cs
  Application/Commands/ClassRoom/UpdateClassRoom/UpdateClassRoomCommandHandler.cs
  Application/Commands/Classrooms/AddClassroom/AddClassroomCommand.cs
  Application/Commands/Classrooms/AddClassroom/AddClassroomCommandHandler.cs
  Application/Commands/Classrooms/DeleteClassroom/DeleteClassroomCommand.cs
  Application/Commands/Classrooms/DeleteClassroom/DeleteClassroomCommandHandler.cs
  Application/Commands/Classrooms/UpdateClassroom/UpdateClassroomCommand.cs
  Application/Commands/Classrooms/UpdateClassroom/UpdateClassroomCommandHandler.cs
  Application/Dtos/ClassRoomDto.cs
  Application/Queries/ClassRoom/GetAllClassRooms/GetAllClassRoomsQuery.cs
  Application/Queries/ClassRoom/GetAllClassRooms/GetAllClassRoomsQueryHandler.cs
  Application/Queries/ClassRoom/GetClassRoomById/GetClassRoomByIdQuery.cs
  Application/Queries/ClassRoom/GetClassRoomById/GetClassRoomByIdQueryHandler.cs
  Application/Queries/Classrooms/GetAllClassrooms/GetAllClassroomQuery.cs
  Application/Queries/Classrooms/GetAllClassrooms/GetAllClassroomQueryHandler.cs
  Application/Queries/Classrooms/GetClassroomsById/GetClassroomByIdQuery.cs
  Application/Queries/Classrooms/GetClassroomsById/GetClassroomByIdQueryHandler.cs
  Domain/Models/ClassRoom/ClassRoom.cs
  Domain/Models/Classrooms/Classroom.cs
  Infrastructure/Database/AppDbContext.cs
  Infrastructure/Database/DbSeed/DbSeed.cs
  Infrastructure/DependencyInjection.cs
  Infrastructure/Migrations/AppDbContextModelSnapshot.cs
  Infrastructure/Repositories/ClassRoom/ClassRoomRepository.cs
  Infrastructure/Repositories/ClassRoom/IClassRoomRepository.cs
  Infrastructure/Repositories/Classrooms/ClassroomRepository.cs
  Infrastructure/Repositories/Classrooms/IClassroomRepository.cs
  Infrastructure/Repositories/Teachers/TeacherRepository.cs
  ReactApp/ReactApp.Server/Controllers/ClassRoomController/ClassRoomController.cs
  Tests/Classroom/Queries/GetAll/GetAllClassroomControllerTests.cs
  Tests/Classroom/Queries/GetAll/GetAllClassroomTests.cs
  Tests/Tests.csproj
Labels: Peppe
